# Generated by Django 5.0 on 2024-03-31 17:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('summarizer_app', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='HistoryItem',
        ),
    ]
